language: python
python:
  - 3.6
sudo: required
services:
  - docker
script:
  - make test-in-container SELECTORS="--distro fedora-26-x86_64.yaml --multispec-selector variant=upstream"
notifications:
  email: false
