language: python
python:
  - 3.6
sudo: required
services:
  - docker
script:
  - make DG="docker run -v $(pwd):/var/dgdir slavek/distgen" GOMD2MAN="docker run -v $(pwd):/go/src/github.com/cpuguy83/go-md2man cpuguy83/go-md2man" build
notifications:
  email: false
