.TH "DOVECOT" "1" " Container Image Pages" "Petr Hracek" "Jun 1, 2017" 
.nh
.ad l


.SH NAME
.PP
dovecot \- Secure imap and pop3 server


.SH DESCRIPTION
.PP
Dovecot container for IMAP server.

.PP
The container itself consists of:
    \- Fedora\-26\-Boltron baseruntime image
    \- dovecot RPM package

.PP
Files added to the container during docker build include: /files/start.sh


.SH USAGE
.PP
To get the memcached container image on your local system, run the following:

.PP
.RS

.nf
docker pull hub.docker.io/modularitycontainers/postfix

.fi
.RE


.SH VOLUMES.IP \(bu 2

.PP
/var/spool/postfix \- contains directories for socket communication with Postfix.
.IP \(bu 2

.PP
/var/spool/mail \- contains directories for INBOXes.


.SH SEE ALSO
.PP
Dovecot page

\[la]https://www.dovecot.org/\[ra]
