#!/bin/bash

source /files/common.sh

if [[ ! -z "${DEBUG_MODE}" ]]; then
    rpm -q syslog-ng
    if [[ $? -ne 0 ]]; then
        dnf -y --setopt=tsflags=nodocs install syslog-ng && \
        dnf -y clean all
        syslog-ng
    fi
fi

if [[ ! -z "${PLAIN_AUTH}" ]]; then
    cat << EOF > /etc/dovecot/conf.d/auth-passwdfile.conf.ext
# File generated by dovecot image
passdb {
  driver = passwd-file
  args = scheme=CRYPT username_format=%u /etc/dovecot/users
}
userdb {
  driver = passwd-file
  args = username_format=%u /etc/dovecot/users
}
EOF
    echo "ssl = no" >> /etc/dovecot/dovecot.conf
    echo '!include auth-passwdfile.conf.ext' >> /etc/dovecot/conf.d/10-auth.conf
fi

dovecot

while true; do
    dovecot_pid=$(cat /var/run/dovecot/master.pid)
	if [[ ! -d "/proc/$PID" ]]; then
	    echo "Dovecot process $dovecot_pid does not exist."
	    break
	fi
	sleep 10
done
